name: mind_track
description: "Digitizes daily activity schedules for individuals with mental illness; allows occupational therapists to monitor progress and provide personalized follow-ups in real time."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ðŸ‘ˆ Added for app icon generation

flutter_icons:  # ðŸ‘‡ App icon configuration
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"   # Optional: background color for Android adaptive icons
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/tasks/
    - assets/tasks/female/
    - assets/tasks/male/